[package]
name = "conventional-commits-changelog-generator"
description = "A CLI and library for generating the changelog based on conventional commits."
version = "0.0.0"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/conventional-commits-rs/conventional-commits-changelog-generator"
authors = ["Sven Lechner <SirWindfield@users.noreply.github.com>"]
edition = "2018"

[dependencies]
conventional-commits-parser = "0.1.0"
git2 = "0.13.8"
markdown-composer = "0.1.0"
semver = "0.10.0"
conventional-commits-next-semver = "0.1.1"
chrono = "0.4.13"

[patch.crates-io]
markdown-composer = { path = "../markdown-composer" }
